### ISSUE TITLE
[ADD] 플레이어의 표정 변화 애니메이션

### ISSUE THREAD

**Issue by hookSSi** [ctw0727/BDP#10]
**어떤 점이 불편한지**
플레이어의 표정 변화 애니메이션을 추가하고 싶습니다.

**그 문제를 해결할 방법**
1. 평상시 표정
2. 피격시 표정
3. 추락할 때 표정
4. 공격 차징 표정
5. 공격 성공 표정

**추가사항**
다른 추가할 표정이 있다면 이야기 가능

**Comment by Seeeeerial** [comment]
2. 피격 시엔 빨간 화면으로,
전체적으로 초록 화면
