### ISSUE TITLE
[ADD] 바닥 이동 파티클

### ISSUE THREAD

**Issue by nsih** [ctw0727/BDP#20]
**어떤 점이 불편한지**
불꽃이 튀는거 설명들은것 같은데 이슈에 없네요

**그 문제를 해결할 방법**

**그 외에 또다른 방법**

**추가사항**

**Comment by hookSSi** [comment]
그럼 물어보고 불꽃이 어떻게 튀어야 한다는지를 적어줘 이건 질문이잖아!
