### ISSUE TITLE
[GRAPHIC] 적 및 공격 관력 그래픽 요청 (1)

### ISSUE THREAD

**Issue by ctw0727** [ctw0727/BDP#21]
**간단한 설명**
- 튜토리얼 스테이지에 배치될 터렛 스프라이트
- 기본 총알 스프라이트

**상세 설명**
이미지 참고 부탁드립니다.
터렛이 파괴될 경우 머리 부분과 몸체, 다리 부분이 분리되도록 할 예정이므로
분리된 머리, 몸체, 다리도 하나씩 따로 준비해주셨으면 합니다.

**참고용 이미지**
![터렛_총알_1](https://user-images.githubusercontent.com/66816721/113831665-d0f37d80-97c2-11eb-8b1e-fc065743a458.jpg)
![터렛_총알_2](https://user-images.githubusercontent.com/66816721/113831679-d3ee6e00-97c2-11eb-9410-ea6b2d044d48.jpg)

**Comment by Seeeeerial** [comment]
일단 확인
나중에 작업할때 질문사항 생기면 말함
