### ISSUE TITLE
[ADD] 배경음 왜곡

### ISSUE THREAD

**Issue by nsih** [ctw0727/BDP#26]
**어떤 점이 불편한지**
클릭해서 기를 모을때(?) 배경음 왜곡이 있으면 좋을것 같다

**그 문제를 해결할 방법**
배경음을 왜곡시킨다.

**그 외에 또다른 방법**
왜곡된 배경음을 쓴다.

**추가사항**
사운드 관리

**Comment by ctw0727** [comment]
좋을 거 같네요!
