### ISSUE TITLE
[Q] 게임의 해상도?

### ISSUE THREAD

**Issue by hookSSi** [ctw0727/BDP#4]
**어느 부분에서 어떤 점이 궁금한지**
게임의 목표 해상도가 어느 정도인지 궁금합니다.

지금은 1920x1080으로 테스트하고 있는 데 짤린 부분이 보여서 물어봅니다.

**Comment by ctw0727** [comment]
임시 보스 스테이지를 만들 때 화면 크기를 상정하지 않고 만들어 일어난 문제같습니다.
목표 해상도는 1920x1080이 맞습니다.
