### ISSUE TITLE
[ADD] 용어를 통일하는 건 어떨까요?

### ISSUE THREAD

**Issue by hookSSi** [ctw0727/BDP#5]
**어떤 점이 불편한지**
여기 프로젝트 명은 BDP 게임 내에 있는 접두어는 ctw 게임 이름은 box smasher

뭔가 통일이 안되어서 협업을 하게되면 이름을 어떻게 지을 지 난해한데

통일을 하는 건 어떨까요?

**그 문제를 해결할 방법**
접두어를 BS_ 로 통일?

**그 외에 또다른 방법**
다른 접두어로 통일할 수 있도록 정해주면 될거 같네요!

**Comment by ctw0727** [comment]
1학년 동기들과 개발 후 합치는 것을 목표로 개발하던 프로젝트라 접두어로 이름 이니셜을 이용하였습니다.
접두어는 BS_로 통일하는 게 더 나을 것 같네요.
