### ISSUE TITLE
[ADD] 보스 패턴 AI에 대하여

### ISSUE THREAD

**Issue by hookSSi** [ctw0727/BDP#7]
**어떤 점이 불편한지**
보스 패턴을 구성하기가 복잡하고 이해하기 어려워질 것 같아서 방안을 가져왔습니다.

**그 문제를 해결할 방법**
빌더 패턴을 사용하는 행동 트리를 사용하는 겁니다! 라고 말하면 좀 어렵네요...

자세히 설명하자면 AI를 트리처럼 노드를 연결하듯이 짜보자는 겁니다.

그것의 대표적인 예시가 행동 트리인데 특히 복잡한 AI에 특화된 자료구조라서 좋습니다.

빌더 패턴은 개념으로 설명하면 좀 어려우니 다음의 그림처럼 코딩하게 클래스 구조를 짠다고 보시면됩니다.

```C#
_tree = new BehaviorTreeBuilder(gameObject)
    .Sequence()
        .Condition("Custom Condition", () => {
            return true;
        })
        .Do("Custom Action", () => {
            return TaskStatus.Success;
        })
    .End()
    .Build();
```

**그 외에 또다른 방법**
제일 이상적인 것은 직접 구현해보는 것인데

실력도 오르고 여러모로 도움 될테니깐요

문제는 시간이죠 시간...

그러니 오픈 소스 유니티 패키지가 많으니 그것을 사용하는 것이 한 가지 방안이 되겠습니다.

**추가사항**
아무래도 저도 잘 모르는 트리라 독학을 하면서 해야 할테니 같이 할 사람이 없다면 

저 혼자 개인적으로 최대한 빨리 해보겠습니다.

흥미가 있다면 같이 공부하면서 구현해도 됩니다.

**Comment by ctw0727** [comment]
행동 트리와 빌더 패턴에 대해 어떤 내용인지 찾아보느라 답변이 늦었습니다.

제가 제대로 이해했는지 확인부탁드립니다.

행동 트리를 통해 보스의 패턴을 결정하고
빌더 패턴에 보스 패턴 관련 정보를 넣어 보스의 패턴을 반환하는 방식으로 코드 복잡성을 줄이자는 내용이 맞나요?

**Comment by hookSSi** [comment]
정확히는 행동 트리를 통해 보스의 패턴이 돌아가고 빌더 패턴을 통해 그 트리를 구성 시키면 코드의 복잡성이 줄어듭니다.

네 그냥 코드의 복잡성을 줄이자는 이야기 입니다!

잘되면 이게 시각화하기도 좋기 때문에 미래에도 좋을 거라고 생각합니다.

**Comment by ctw0727** [comment]
아직 빌더 패턴이나 자바 언어에 대한 이해도가 부족해서 빌더 패턴을 통해 트리를 구성하는 데에서 어떤 이득이 생기는지 잘 모르겠습니다...

일단 코드 작성 진행해주시면 보고 배우도록 하겠습니다

**Comment by hookSSi** [comment]
이렇게 한다고 드라마틱한 변화는 없지만 미래에는 반드시 편하게 코딩할 수 있습니다.

자세한건 디코로 알려드리겠습니다만 꼭 해야한다는 건 아니고 권장사항인 느낌입니다.
